### ISSUE TITLE
Make a vector version of the GitHub graphic label for better look on Retina screens

### ISSUE THREAD

**Issue by shvechikov** [svetlyak40wt/allmychanges#11]
Demo:
![](http://i.imgur.com/8227rCD.png)

Example:
![](https://camo.githubusercontent.com/c79303bbf0761ef1b8dfdc2e1ed801140407e58d/68747470733a2f2f696d672e736869656c64732e696f2f707970692f762f646a616e676f2d7363686564756c65722e737667)

Screenshot has been taken from here — https://github.com/llazzaro/django-scheduler

**Comment by svetlyak40wt** [comment]
Done
